name: Mirror to GitHub
on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote add github https://$GITHUB_TOKEN@github.com/Shatti/ha-custom-components.git
          git fetch --unshallow
          git push github --all --force
          git push github --tags --force