name: Mirror to GitHub
on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: local
    steps:
      - name: Mirror to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd $(mktemp -d)
          git clone --mirror https://gitea.shatto.cloud/Shatti/ha-custom-components.git .
          git remote add github https://${GITHUB_TOKEN}@github.com/Shatti/ha-custom-components.git
          git push --mirror github