name: Mirror to GitHub
on:
  push:
    branches:
      - main


jobs:
  mirror:
    runs-on: local
    steps:
      - name: Checkout
        run: |
          git clone --mirror ${GITEA_REPO_URL} .
          git remote add github ${GITHUB_REPO_URL}
          git push --mirror github
        env:
          GITEA_REPO_URL: ${{ secrets.GITEA_REPO_URL }}
          GITHUB_REPO_URL: https://${{ secrets.GITHUB_ACCESS_TOKEN }}@github.com/Shatti/ha-custom-components.git